#ifndef SARA_DEFINE_H_
#define SARA_DEFINE_H_

#define SARA_AT_ECHO "AT"

#define SARA_AT_ECHO_OFF "ATE0"

#define SARA_AT_CHECK_MFR       "AT+GMI"
#define SARA_AT_CHECK_MODEL     "AT+GMM"
#define SARA_AT_CHECK_FW        "AT+GMR"
#define SARA_AT_CHECK_IMEI      "AT+GSN"
#define SARA_AT_CHECK_IMSI      "AT+CIMI"
#define SARA_AT_CHECK_SIM_ID    "AT+CCID"
#define SARA_AT_CHECK_SUB_NUM   "AT+CNUM"
#define SARA_AT_POWER_OFF       "AT+CPWROFF"

#define SARA_AT_SET_MASTER_CLOCK_DISABLE    "AT+UMCLK=0,0"
#define SARA_AT_SET_GNSS_DISABLE    "AT+UGIND=0"

#define SARA_AT_NET_CHECK_OP_LIST   "AT+COPS=?"
#define SARA_AT_NET_CHECK_GATT      "AT+CGATT?"
#define SARA_AT_NET_ACT_GPRS        "AT+UPSDA=0,3"
#define SARA_AT_NET_CHECK_GPRS      "AT+UPSND=0,8"

#define SARA_AT_NET_CHECK_BAND      "AT+UBANDSEL?"
#define SARA_AT_NET_CHECK_OPERATOR  "AT+UDOPN=4"
#define SARA_AT_NET_CHECK_EONS      "AT+UEONS"
#define SARA_AT_NET_REQ_LIST    "AT+GCAP"

#define SARA_AT_CHECK_PHONE_ACTIVITY    "AT+CPAS"

#define SARA_AT_HTTP_FILE_DELETE_PREV_POST "AT+UDELFILE=\"postdata.txt\""
#define SARA_AT_HTTP_FILE_DELETE_PREV_RESPONSE "AT+UDELFILE=\"result.txt\""
#define SARA_AT_HTTP_FILE_WRITE "AT+UDWNFILE"
#define SARA_AT_HTTP_PROFILE    "AT+UHTTP=0"
#define SARA_AT_HTTP_SET_DOMAIN "AT+UHTTP=0,1"
#define SARA_AT_HTTP_SET_PORT   "AT+UHTTP=0,5,80"
#define SARA_AT_HTTP_POST       "AT+UHTTPC=0,4"
#define SARA_AT_HTTP_GET        "AT+UHTTPC=0,1"
#define SARA_AT_HTTP_CHECK_DATA "AT+URDFILE=\"postdata.txt\""
#define SARA_AT_HTTP_RESPONSE   "AT+URDFILE=\"result.txt\""

#define SARA_AT_GPIO_1_NETWORK_STATE "AT+UGPIOC=16,2,0"

#define SARA_AT_POWER_CHECK "AT+UPSV?"
#define SARA_AT_POWER_SAVE_1 "AT+UPSV=1"
#define SARA_AT_POWER_SAVE_2 "AT+UPSV=2"
#define SARA_AT_POWER_SAVE_3 "AT+UPSV=3"

#define SARA_AT_POWER_SAVE_MODE_OFF "AT+UPSV=0"

#define SARA_AT_SOCKET_CMD_CREATE "AT+USOCR=6"
#define SARA_AT_SOCKET_CMD_CLOSE "AT+USOCL=0"
#define SARA_AT_SOCKET_CMD_CONNECT "AT+USOCO=0"
#define SARA_AT_SOCKET_CMD_WRITE "AT+USOWR=0"
#define SARA_AT_SOCKET_EVT_CLOSE "+UUSOCL"
#define SARA_AT_NETWORK_RESOLVE_NAME "AT+UDNSRN=0"

#define SARA_AT_NET_SIG_QUAL    "AT+CSQ"
#define SARA_AT_NET_REG_STAT    "AT+CREG"
#define SARA_AT_NET_SEL_BAND    "AT+UBANDSEL"
#define SARA_AT_NET_CELL_INFO   "AT+UCELLINFO"
#define SARA_AT_NET_SUB_NUM     "AT+CNUM"
#define SARA_AT_NET_REG_STATUS  "AT+CREG=?"

#define SARA_AT_INT_SSL_MOD     "AT+USOSEC"
#define SARA_AT_INT_SOC_CR      "AT+USOCR"
#define SARA_AT_INT_SOC_SET_OP  "AT+USOSO"
#define SARA_AT_INT_SOC_GET_OP  "AT+USOGO"
#define SARA_AT_INT_SOC_CLOSE   "AT+USOCL"
#define SARA_AT_INT_SOC_GET_ERR "AT+USOER"
#define SARA_AT_INT_SOC_CONN    "AT+USOCO"
#define SARA_AT_INT_SOC_WR_DATA "AT+USOWR"
#define SARA_AT_INT_SOC_RD_DATA "AT+USORD"
#define SARA_AT_INT_SOC_SET_LITN    "AT+USOLI"
#define SARA_AT_INT_SOC_FIREWALL    "AT+UFRW"
#define SARA_AT_INT_SOC_CTRL        "AT+USOCTL"
#define SARA_AT_INT_SOC_IP_CHANGE_NOTI  "AT+UIPCHGN"

#define SARA_AT_PROFILE_CMD "AT&Y1"
#define SARA_AT_PROFILE_SAVE "AT&W1"
#define SARA_AT_SHOW_PROFILE "AT&V"
#define SARA_AT_SAVE_PARAMTER_AND_RESET "AT+CFUN=15"

#endif /* SARA_DEFINE_H_ */
